name: Elley
version: '${project.version}'
main: dev.revere.alley.AlleyPlugin
authors: [ "Emmy", "Remi", "Calimarri" ]
description: 'Custom fork of Alley for EB Practice'
website: dsc.gg/ebeagler
depend:
  - FastAsyncWorldEdit
softDepend:
  - PlaceholderAPI
